### ISSUE TITLE
Some dists listed twice in no-license

### ISSUE THREAD

**Issue by openstrike** [szabgab/metacpanjs#1]
I've just spotted that some dists (eg. CGI-RSS, SQL-Steno, B-Flags) are listed on http://cpan.perlmaven.com/#no-license twice. Others (eg. Apache-Test) are only listed once.

As there's no obvious sorting of the dists on this page, I can only guess that the duplicate entries are a bug.

**Comment by szabgab** [comment]
Some of those were probably duplicate because the author has released two version in a short period of time. The text on the link now includes the version number of the distribution. This should eliminate most of those cases. However there are cases when MetaCPAN reports the same version number uploaded twice. For example on Sunday, 10 May 2015 the  https://metacpan.org/recent listing includes two copies of MobileDetect-1.18 because there were two uploads by two authors. (One of them was unauthorized).

This is probably related to https://github.com/CPAN-API/metacpan-web/issues/1382

I don't know what MetaCPAN should do in such cases and how should that be displayed.

Thanks for reporting.
